server:
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  port: 9000
  shutdown: graceful

spring:
  application:
    name: edge-svr
  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        - id: default-route
          uri: ${ROUTE_DEFAULT:http://localhost:9001}/
          order: 0
          predicates:
            - Path=/, /css/**, /js/**, /img/**, /icon/**
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  lifecycle:
    timeout-per-shutdown-phase: 15s
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-svr
            client-secret: portal-keycloak-secret
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/Portal}
  session:
    timeout: 10m
    redis:
      namespace: portal:edge
