server:
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  port: 9000
  shutdown: graceful

spring:
  application:
    name: edge-svr
  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        - id: 0-test
          filters:
            - TokenRelay=
          order: 0
          predicates:
            - Method=GET
            - Path=/test/token
          uri: ${ROUTE_DEFAULT:http://localhost:9001}/
        - id: 1-run
          order: 1
          predicates:
            - Method=GET,POST
            - Path=/run
          uri: ${ROUTE_RUN:http://localhost:9002}/
        - id: 100-default
          order: 100
          predicates:
            - Path=/, /css/**, /js/**, /img/**, /icon/**
          uri: ${ROUTE_DEFAULT:http://localhost:9001}/
  data:
    redis:
      connect-timeout: 2s
      host: portal-redis
      port: 6379
      timeout: 1s
  lifecycle:
    timeout-per-shutdown-phase: 15s
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-svr
            client-secret: portal-keycloak-secret
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/Portal}
  session:
    timeout: 10m
    redis:
      namespace: portal:edge
