server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-svr
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      routes:
        - id: default-route
          uri: ${ROUTE_DEFAULT:http://localhost:9001}/
          order: 1
          predicates:
            - Path=/
        - id: keycloak-route
          uri: ${ROUTE_KEYCLOAK:http://localhost:8080/realms/Portal}/
          order: 0
          predicates:
            - Path=/realms/, /oauth2/
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-svr
            client-secret: portal-keycloak-secret
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/Portal}
